import { tool } from "@langchain/core/tools"
import { z } from "zod"
import { mkdir } from "node:fs/promises"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { getAppBrowserEndpoint } from "../app-browser.ts"
import { CdpClient, validateHttpUrl, type CdpNode } from "../cdp.ts"
import { toolResult } from "./result.ts"

let client: CdpClient | undefined
let url = "", title = ""
function getClient() { const e = getAppBrowserEndpoint(); if (!e || !e.debuggable) throw new Error("The Chunky desktop app isn't running / its browser pane isn't CDP-capable — ask the user to open the app") ; return client ??= new CdpClient(e.cdpUrl) }
async function snapshot(c = getClient()) { const r = await c.command<{ nodes: CdpNode[] }>("Accessibility.getFullAXTree"); const { text, refs } = (await import("../cdp.ts")).interestingOutline(r.nodes ?? []); c.setRefs(refs); try { const x = await c.command<any>("Runtime.evaluate", { expression: "document.title", returnByValue: true }); title = String(x.result?.value ?? "") } catch {} ; try { const x = await c.command<any>("Runtime.evaluate", { expression: "location.href", returnByValue: true }); url = String(x.result?.value ?? "") } catch {} ; return `URL: ${url}\nTitle: ${title}\n${text.slice(0, 18000)}${text.length > 18000 ? "\n[truncated; re-snapshot]" : ""}` }
function fail(e: unknown) { return toolResult(e instanceof Error ? e.message : String(e), { ok: false }) }
async function box(c: CdpClient, ref: string) { const id = c.ref(ref); if (!id) throw new Error(`Unknown or stale ref ${ref}; call browser_snapshot again after navigation.`); const r = await c.command<any>("DOM.getBoxModel", { backendNodeId: id }); const q = r.model?.content ?? r.model?.border; if (!q?.length) throw new Error(`Element ${ref} is not visible; call browser_snapshot again.`); return { id, x: (q[0] + q[2] + q[4] + q[6]) / 4, y: (q[1] + q[3] + q[5] + q[7]) / 4 } }
const browser_navigate = tool(async ({ url: target }: { url: string }) => { const error = validateHttpUrl(target); if (error) return toolResult(error, { ok: false }); try { const c = getClient(); await c.command("Page.navigate", { url: target }); await new Promise(r => { const off = c.on("Page.loadEventFired", () => { off(); r(undefined) }); setTimeout(() => { off(); r(undefined) }, 5000) }); return toolResult(await snapshot(c)) } catch (e) { return fail(e) } }, { name: "browser_navigate", description: "Navigate the user's browser pane to an http(s) URL and return its accessibility snapshot.", schema: z.object({ url: z.string() }) })
const browser_snapshot = tool(async () => { try { return toolResult(await snapshot()) } catch (e) { return fail(e) } }, { name: "browser_snapshot", description: "Read the user's browser pane as a compact accessibility tree with stable element refs.", schema: z.object({}) })
const browser_click = tool(async ({ ref }: { ref: string }) => { try { const c = getClient(); const b = await box(c, ref); await c.command("Input.dispatchMouseEvent", { type: "mousePressed", x: b.x, y: b.y, button: "left", clickCount: 1 }); await c.command("Input.dispatchMouseEvent", { type: "mouseReleased", x: b.x, y: b.y, button: "left", clickCount: 1 }); return toolResult(`Clicked ${ref}. If the page navigated, call browser_snapshot again.`) } catch (e) { return fail(e) } }, { name: "browser_click", description: "Click a browser element by snapshot ref.", schema: z.object({ ref: z.string() }) })
const browser_type = tool(async ({ ref, text, submit }: { ref: string; text: string; submit?: boolean }) => { try { const c = getClient(); const b = await box(c, ref); await c.command("DOM.focus", { backendNodeId: b.id }); await c.command("Input.dispatchKeyEvent", { type: "keyDown", key: "a", code: "KeyA", modifiers: 2 }); await c.command("Input.dispatchKeyEvent", { type: "keyUp", key: "a", code: "KeyA", modifiers: 2 }); await c.command("Input.insertText", { text }); if (submit) await press(c, "Enter"); return toolResult(`Typed into ${ref}.`) } catch (e) { return fail(e) } }, { name: "browser_type", description: "Focus an input by ref and type text, optionally submitting it.", schema: z.object({ ref: z.string(), text: z.string(), submit: z.boolean().optional() }) })
const keyCodes: Record<string, number> = { Enter: 13, Tab: 9, Escape: 27, ArrowDown: 40, ArrowUp: 38, ArrowLeft: 37, ArrowRight: 39, Backspace: 8, Delete: 46, Home: 36, End: 35 }
async function press(c: CdpClient, key: string) { const code = keyCodes[key]; if (!code) throw new Error(`Unsupported key ${key}`); await c.command("Input.dispatchKeyEvent", { type: "keyDown", key, windowsVirtualKeyCode: code }); await c.command("Input.dispatchKeyEvent", { type: "keyUp", key, windowsVirtualKeyCode: code }) }
const browser_press_key = tool(async ({ key }: { key: string }) => { try { await press(getClient(), key); return toolResult(`Pressed ${key}.`) } catch (e) { return fail(e) } }, { name: "browser_press_key", description: "Press a common keyboard key in the browser pane.", schema: z.object({ key: z.string() }) })
const browser_scroll = tool(async ({ direction = "down", ref }: { direction?: string; ref?: string }) => { try { const c = getClient(); const b = ref ? await box(c, ref) : { x: 400, y: 300 }; const dy = direction === "up" ? -600 : direction === "left" ? 0 : 600; const dx = direction === "left" ? -600 : direction === "right" ? 600 : 0; await c.command("Input.dispatchMouseEvent", { type: "mouseWheel", x: b.x, y: b.y, deltaX: dx, deltaY: dy }); return toolResult(`Scrolled ${direction}.`) } catch (e) { return fail(e) } }, { name: "browser_scroll", description: "Scroll the browser pane up or down, optionally near a ref.", schema: z.object({ direction: z.enum(["up", "down", "left", "right"]).optional(), ref: z.string().optional() }) })
async function history(delta: number) { const c = getClient(); const h = await c.command<any>("Page.getNavigationHistory"); const i = h.currentIndex + delta; if (i < 0 || i >= h.entries.length) throw new Error("No browser history entry in that direction."); await c.command("Page.navigateToHistoryEntry", { entryId: h.entries[i].id }); return toolResult(await snapshot(c)) }
const browser_back = tool(async () => { try { return await history(-1) } catch (e) { return fail(e) } }, { name: "browser_back", description: "Go back in the browser pane history.", schema: z.object({}) })
const browser_forward = tool(async () => { try { return await history(1) } catch (e) { return fail(e) } }, { name: "browser_forward", description: "Go forward in the browser pane history.", schema: z.object({}) })
const browser_screenshot = tool(async () => { try { const data = await getClient().command<any>("Page.captureScreenshot", { format: "png" }); const dir = join(tmpdir(), "chunky-browser"); await mkdir(dir, { recursive: true }); const path = join(dir, `screenshot-${Date.now()}.png`); await Bun.write(path, Uint8Array.from(atob(data.data), c => c.charCodeAt(0))); return toolResult(`Screenshot saved to ${path}`, { raw: { path } }) } catch (e) { return fail(e) } }, { name: "browser_screenshot", description: "Capture the user's browser pane to a PNG file.", schema: z.object({}) })
const browser_evaluate = tool(async ({ expression }: { expression: string }) => { try { const r = await getClient().command<any>("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true }, 10000); const out = JSON.stringify(r.result?.value ?? r.result?.description ?? null); return toolResult(out.length > 18000 ? `${out.slice(0, 18000)}\n[truncated]` : out) } catch (e) { return fail(e) } }, { name: "browser_evaluate", description: "Evaluate JavaScript in the browser pane and return its value.", schema: z.object({ expression: z.string() }) })
export const browserTools = [browser_navigate, browser_snapshot, browser_click, browser_type, browser_press_key, browser_scroll, browser_back, browser_forward, browser_screenshot, browser_evaluate]
