import {Session} from './session.ts';import {createServer,connect} from 'node:net';import {mkdirSync,chmodSync,existsSync,unlinkSync,openSync,closeSync} from 'node:fs';import {join} from 'node:path';import {encodeMessage,LineAccumulator} from './protocol.ts';
const dir=process.env.TERMCTRL_RUNTIME_DIR??`/tmp/termctrl-${process.getuid?.()??0}`;export type Launch={command:string[];cwd:string;record?:string;cols:number;rows:number;cell_width:number;cell_height:number;max_bytes:number;opentui_host?:string;color?:string};export type ProcessExit={code:number;signal:string|null;success:boolean};export type Status={state:'running'|'exited';exit:ProcessExit|null;cols:number;rows:number;cell_width:number;cell_height:number;idle_for_ms:number|null;has_visible_content:boolean;recording:boolean;logs_truncated:boolean;launch:Launch};
export const socketPath=(n:string)=>join(dir,`${n}.sock`),lockPath=(n:string)=>join(dir,`${n}.lock`);export function ensureDir(){if(!existsSync(dir))mkdirSync(dir,{recursive:true,mode:0o700});chmodSync(dir,0o700)}
export async function request(name:string,msg:any):Promise<any>{return new Promise((resolve,reject)=>{const s=connect(socketPath(name));const acc=new LineAccumulator();let settled=false;s.on('data',(x:Buffer)=>{try{for(const value of acc.push(x)){if(settled)continue;settled=true;const o:any=value;o.error?reject(Error(o.error)):resolve(o.result);s.destroy()}}catch(e){reject(e);s.destroy()}});s.on('error',e=>{if(!settled)reject(e)});s.on('connect',()=>s.write(encodeMessage(msg)))})}
export function acquire(name:string){ensureDir();try{const fd=openSync(lockPath(name),'wx',0o600);return fd}catch{if(!existsSync(socketPath(name))){try{unlinkSync(lockPath(name))}catch{};return openSync(lockPath(name),'wx',0o600)}throw Error(`session ${name} is already locked`)}}
export function release(name:string,fd:number){closeSync(fd);try{unlinkSync(lockPath(name))}catch{}}
export function serve(socket:string,launch:Launch){const name=socket.split('/').pop()!.replace(/\.sock$/,'');const lock=acquire(name);const s=new Session(launch.command,{cwd:launch.cwd,cols:launch.cols,rows:launch.rows,maxBytes:launch.max_bytes,record:launch.record,cellWidth:launch.cell_width,cellHeight:launch.cell_height});const server:any=createServer(sock=>{const acc=new LineAccumulator();let done=false;const reply=(value:any)=>{const wire=encodeMessage(value);sock.write(wire,()=>sock.end())};const handle=async(m:any)=>{if(done)return;done=true;try{const r=await dispatch(s,m,server,socket);reply({result:r})}catch(e){reply({error:String(e instanceof Error?e.message:e)})}};sock.on('data',(x:Buffer)=>{try{for(const m of acc.push(x))void handle(m)}catch(e){reply({error:String(e)})}})});server.__termctrlRelease=()=>release(name,lock);server.listen(socket,()=>chmodSync(socket,0o600));}
async function dispatch(s:Session,m:any,server:any,socket:string){switch(m.method){case'ping':return true;case'status':return status(s);case'capture':return s.capture(m.settle_ms??250,m.deadline_ms??5000);case'wait':await s.waitForText(m.text,m.timeout_ms??5000);return null;case'send':s.send(Uint8Array.from(m.bytes));return null;case'resize':s.resize(m.cols,m.rows);return null;case'mark':s.marker(m.name);return null;case'logs':return Array.from(s.ansi);case'stop':s.stop();server.close(()=>{try{unlinkSync(socket)}catch{};server.__termctrlRelease?.()});return null;default:throw Error('unknown request')}}
function status(s:Session):Status{return {state:s.exited?'exited':'running',exit:s.exit,cols:s.terminal.cols,rows:s.terminal.rows,cell_width:9,cell_height:18,idle_for_ms:s.lastOutput===null?null:Date.now()-s.lastOutput,has_visible_content:s.text().trim().length>0,recording:!!s.recordPath,logs_truncated:s.logsTruncated,launch:{command:s.command,cwd:s.cwd,record:s.recordPath,cols:s.terminal.cols,rows:s.terminal.rows,cell_width:9,cell_height:18,max_bytes:s.maxBytes}}}
export {dir};
